import { writeFileSync } from "node:fs";
import { join } from "node:path";
import type { Report, Status } from "../types.js";

const ICON: Record<Status, string> = { pass: "✅", weak: "🟡", fail: "🔴" };

export function renderMarkdown(report: Report, frameworks: string[]): string {
  const gradeText =
    report.grade === "ready"
      ? "🟢 Production-ready"
      : report.grade === "risky"
        ? "🟡 Risky — patch before shipping"
        : "🔴 Not ready — will likely fail in prod";

  const lines: string[] = [];
  lines.push(`# Agent Production Readiness: ${report.score} / 100`);
  lines.push("");
  lines.push(`**${gradeText}**  ·  Framework: ${frameworks.join(", ")}`);
  lines.push("");
  lines.push("| Check | Status | Score | Notes |");
  lines.push("| --- | --- | --- | --- |");
  for (const ch of report.checks) {
    lines.push(
      `| ${ch.title} | ${ICON[ch.status]} ${ch.status} | ${ch.earned}/${ch.weight} | ${ch.note} |`,
    );
  }
  lines.push("");

  const fixes = report.checks.filter((ch) => ch.status !== "pass" && ch.fix);
  if (fixes.length > 0) {
    lines.push("## How to raise your score");
    lines.push("");
    for (const ch of fixes) {
      lines.push(`- **${ch.title}** — ${ch.fix}`);
    }
    lines.push("");
  }

  lines.push("---");
  lines.push("");
  lines.push(
    "_Generated by [agent-readiness](https://github.com/YOMXXX/agent-readiness). " +
      "88% of agents that demo well fail in production. " +
      "Want a human deep-dive? [Email me for a free audit →](mailto:316195542@qq.com)_",
  );
  lines.push("");
  return lines.join("\n");
}

export function writeMarkdownReport(report: Report, frameworks: string[], dir: string): string {
  const md = renderMarkdown(report, frameworks);
  const out = join(dir, "AGENT-READINESS.md");
  writeFileSync(out, md, "utf8");
  return out;
}
